export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';




export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const PROFESSIONAL_APPOINTMENT = 'PROFESSIONAL_APPOINTMENT';

export const GET_PROFESSIONAL = 'GET_PROFESSIONAL';
export const GET_ALL_PROFESSIONAL = 'GET_ALL_PROFESSIONAL';
export const GET_FILTER_PROFESSIONAL = 'GET_FILTER_PROFESSIONAL';
export const GET_NEW_AVAILABLE_DAY = 'GET_NEW_AVAILABLE_DAY';

export const GET_PATIENS_DATA = 'GET_PATIENS_DATA';
export const SET_JOURNAL = 'SET_JOURNAL';

export const SET_PATIEN_JOURNAL = 'SET_PATIEN_JOURNAL';


